# Generated by Django 2.0.7 on 2018-07-15 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(max_length=60, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='Perfil_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120, null=True)),
                ('apellidos', models.CharField(max_length=80, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, default='fotos_usuarios/avatar.png', upload_to='fotos_usuarios')),
                ('celular', models.DecimalField(decimal_places=0, max_digits=9, max_length=9, null=True)),
                ('codigo_pais', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(choices=[('Peru', 'Perú'), ('Bolivia', 'Bolivia'), ('Chile', 'Chile'), ('Ecuador', 'Ecuador'), ('Colombia', 'Colombia'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Mexico', 'Mexico'), ('Otros', 'Otros')], default='Peru', max_length=50)),
                ('ciudad', models.CharField(max_length=80, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=120, null=True)),
                ('profesion', models.CharField(blank=True, max_length=120, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfil Usuarios',
                'verbose_name': 'Perfil Usuario',
            },
        ),
    ]
